logging.file.name=/app/logs/app.log
logging.level.root=INFO
# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Enable Prometheus metrics export
management.metrics.export.prometheus.enabled=true
event.batch.flush-interval-millis=5000
event.s3.bucket=ruchita-events
event.s3.region=eu-north-1
event.batch.max-size-bytes=5242880
event.valid-customer-tiers=gold,silver,platinum
event.aws.accessKeyId=<accessKeyId>
event.aws.secretAccessKey=<secretAccessKey>
